### PR TITLE
Add section for Ticket/Request Submissions

### PR DESCRIPTION
**Pull request by jzcardoso**
Add section for Ticket/Request Submissions to provide an ongoing reference list.

Signed-off-by: Jacqueline Z Cardoso <45864851+jzcardoso@users.noreply.github.com>

### CODE REVIEW

**Review by wendallkaters — COMMENTED** [review]
I am so glad you did ticketing links! So helpful! @cmassey11 did a section about how to file a ticket to onboard a new contractor. Maybe we should fold her content into this one.

**Review by wendallkaters — APPROVED** [review]

**Comment by wendallkaters** [comment]
Might also be good to include the Member Ops Desk FAQ in this section as well: https://docs.google.com/document/d/1P1K3kzuhaRIoOwj117XB_5SOMjqj2r-ZwZFCFyal6W0/edit

**Comment by jzcardoso** [comment]
> I am so glad you did ticketing links! So helpful! @cmassey11 did a section about how to file a ticket to onboard a new contractor. Maybe we should fold her content into this one.

@wendallkaters Thanks for the review. It's a topic I think many of us struggle to keep track of, glad you agree it is useful! 

Regarding the item @cmassey11 added for onboarding contractors, maybe hers links back to this section since the Legal tickets are referenced here since her section seems a bit more process detailed. Any thoughts here @dplanella?

**Comment by jzcardoso** [comment]
> Might also be good to include the Member Ops Desk FAQ in this section as well: https://docs.google.com/document/d/1P1K3kzuhaRIoOwj117XB_5SOMjqj2r-ZwZFCFyal6W0/edit

@wendallkaters Great idea, I will add this link.

**Review by dplanella — APPROVED** [review]
This is great, thanks @jzcardoso!

> Regarding the item @cmassey11 added for onboarding contractors, maybe hers links back to this section since the Legal tickets are referenced here since her section seems a bit more process detailed. Any thoughts here @dplanella?

I'd agree with that, keep the sections separate and add links where appropriate.

I'll go ahead and merge, as this change already provides good value.

**Pull request merged**
